"use client";
import "./globals.css";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "Tednih | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider enableSystem={true} attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
